/* THE UPDATE CHANNEL. Everything that decides whether an installer runs lives in this file, in the
   MAIN process, and nothing here trusts the renderer or the server.

   Record: docs/desktop-update-channel-plan.md (v2, after two adversarial reviews).

   The five rules the design rests on, each one the answer to a finding rather than a preference:

   1. THE URL IS A CONSTANT. Every other request this app makes is built from `--api-base=`, which is
      settable by anybody who can edit a Start Menu shortcut - no privilege required. That is fine for
      a beacon and an ad card. It is not fine for an endpoint whose answer causes an installer to run,
      so this one is hard-coded. `--update-url=` exists for development and CANNOT INSTALL: a manifest
      fetched through it may only notify.
   2. VERIFY, THEN PARSE. The signature covers opaque bytes with a domain separator. Nothing outside
      `payload` is read, and the JSON is not parsed until Ed25519 has passed.
   3. THE HASH IS CHECKED BEFORE THE FILE IS EXECUTED, from the handle it was written through, with no
      gap: the staging directory is writable by anything running as this user.
   4. WE NEVER GO BACKWARDS, and never sideways: a version at or below our own is refused, and the
      download host is pinned.
   5. NOTHING BLOCKS. Owner decision 2026-08-16: a free, offline build never forces an update.
      There is no floor and no field that could add one.

   Nothing in here throws into the app. Every failure is a silent no-update, because an editor must
   never show an error because our server had a bad day. */
'use strict';

const { app, net, shell } = require('electron');
const fs = require('node:fs');
const fsp = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');
const { pipeline } = require('node:stream/promises');

/* ── constants that are deliberately not configurable ───────────────────────────────────────────── */

const UPDATE_ORIGIN = 'https://app.dika.studio';
const DOMAIN = 'dika.studio/update-manifest/v1\0';
const SCHEMA = 1;

/* THE TRUST ANCHOR. Generated by `node build/update-manifest.mjs keygen` on 2026-08-16; the private
   half never entered this repository and lives only on the owner's machine.

   It is PUBLIC - it can verify a signature and cannot make one - so it belongs in the source rather
   than in a secret store, and being in the source is the point: it ships compiled into the binary,
   where a compromised server cannot swap it. The environment variable stays as an override for the
   proofs, which generate a throwaway key per run.

   Replacing this key means shipping a new binary. That is not a limitation to work around; it is what
   makes the key an anchor instead of a suggestion. */
const UPDATE_PUBLIC_KEY = process.env.DIKA_UPDATE_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAxuVm5SLOZR34ALZdJBbEEuwNitxbneBWQOMcg1bLljo=
-----END PUBLIC KEY-----
`;

/* The artifact host, and the ONE redirect it may take. GitHub has moved this target more than once
   (`objects.` -> `github-releases.` -> `release-assets.`), so the suffix is pinned rather than a host:
   a hard-pinned name in a shipped binary becomes a fleet-wide outage the day they move it again, and
   the repair would have to travel through the channel that is down. The sha512 is the real integrity
   control; this is defence in depth and must not be brittle. */
const ARTIFACT_HOST = 'github.com';
const ARTIFACT_REDIRECT_SUFFIX = '.githubusercontent.com';
const MAX_REDIRECTS = 1;

const FETCH_TIMEOUT_MS = 2000;      // the check. Never let our availability delay somebody's editor.
const MANIFEST_MAX_BYTES = 64 * 1024;
const POSTPONE_DAYS = 7;

/* ── state, in userData, never in the renderer ──────────────────────────────────────────────────── */

let statePath = null;
let state = { minKeyId: '', postponedVersion: '', postponedAt: 0, optOut: false, lastCheckedAt: 0 };
let current = null;                 // the verified, applicable payload, or null
let busy = false;

function loadState() {
  statePath = path.join(app.getPath('userData'), 'update-state.json');
  try { Object.assign(state, JSON.parse(fs.readFileSync(statePath, 'utf8'))); } catch { /* first run */ }
}
function saveState() {
  try { fs.writeFileSync(statePath, JSON.stringify(state, null, 2)); } catch { /* not worth an error */ }
}

/* ── command line ───────────────────────────────────────────────────────────────────────────────── */

const argv = process.argv;
const flag = (name) => {
  const hit = argv.find((a) => a.startsWith('--' + name + '='));
  return hit ? hit.slice(name.length + 3) : null;
};
const DISABLED = argv.includes('--no-update');
const CHANNEL = (flag('update-channel') || 'stable').replace(/[^a-z0-9-]/gi, '') || 'stable';
/* A development override. It changes WHERE we look and permanently removes the ability to install,
   which is what keeps it from being the hole the constant above exists to close. */
const DEV_URL = flag('update-url');
const NOTIFY_ONLY = !!DEV_URL || process.platform !== 'win32';

function manifestUrl() {
  if (DEV_URL) return DEV_URL;
  return UPDATE_ORIGIN + '/api/community/update/' + CHANNEL + '.json';
}

/* ── semver, only as much as we need ────────────────────────────────────────────────────────────── */

function cmpVersion(a, b) {
  const pa = String(a).split('-')[0].split('.').map(Number);
  const pb = String(b).split('-')[0].split('.').map(Number);
  for (let i = 0; i < 3; i++) {
    const x = pa[i] || 0, y = pb[i] || 0;
    if (x !== y) return x < y ? -1 : 1;
  }
  /* A prerelease is LOWER than the release of the same numbers, which is what stops 1.1.0-beta.1 from
     being offered to somebody already on 1.1.0. */
  const qa = String(a).includes('-'), qb = String(b).includes('-');
  if (qa !== qb) return qa ? -1 : 1;
  return 0;
}

/* ── the network ────────────────────────────────────────────────────────────────────────────────── */

/** A bounded GET that resolves to a Buffer, or null. Never throws, never follows a redirect. */
function getBounded(url, maxBytes, timeoutMs) {
  return new Promise((resolve) => {
    let done = false;
    const finish = (v) => { if (!done) { done = true; resolve(v); } };
    let req;
    try {
      req = net.request({
        url, method: 'GET', redirect: 'error',
        /* A fixed, minimal User-Agent. Electron's default carries the app name and version, which is
           precisely the fact this request claims not to send. */
        headers: { 'user-agent': 'dika.studio-updater', accept: 'application/json' }
      });
    } catch { return finish(null); }
    const timer = setTimeout(() => { try { req.abort(); } catch { /* already gone */ } finish(null); }, timeoutMs);
    req.on('response', (res) => {
      if (res.statusCode !== 200) { clearTimeout(timer); try { req.abort(); } catch {} return finish(null); }
      const chunks = []; let size = 0;
      res.on('data', (c) => {
        size += c.length;
        if (size > maxBytes) { clearTimeout(timer); try { req.abort(); } catch {} return finish(null); }
        chunks.push(c);
      });
      res.on('end', () => { clearTimeout(timer); finish(Buffer.concat(chunks)); });
      res.on('error', () => { clearTimeout(timer); finish(null); });
    });
    req.on('error', () => { clearTimeout(timer); finish(null); });
    req.end();
  });
}

/** Failure-only, anonymous, and not consent-gated because it carries no identity. */
function reportFailure(reason, toVersion) {
  if (DEV_URL) return;
  try {
    const req = net.request({ url: UPDATE_ORIGIN + '/api/community/update/failure', method: 'POST',
      headers: { 'content-type': 'application/json', 'user-agent': 'dika.studio-updater' } });
    req.on('error', () => {});
    req.end(JSON.stringify({ fromVersion: app.getVersion(), toVersion: toVersion || null, reason: String(reason).slice(0, 80) }));
  } catch { /* a report that fails is not worth a second failure */ }
}

/* ── verification ───────────────────────────────────────────────────────────────────────────────── */

function verifyManifest(doc) {
  if (!UPDATE_PUBLIC_KEY) throw new Error('no public key compiled in');
  if (!doc || typeof doc !== 'object' || doc.schema !== SCHEMA) throw new Error('schema');
  if (typeof doc.payload !== 'string' || typeof doc.signature !== 'string') throw new Error('shape');
  const payloadBytes = Buffer.from(doc.payload, 'base64url');
  const input = Buffer.concat([Buffer.from(DOMAIN, 'utf8'), payloadBytes]);
  const ok = crypto.verify(null, input, crypto.createPublicKey(UPDATE_PUBLIC_KEY),
    Buffer.from(doc.signature, 'base64url'));
  if (!ok) throw new Error('signature');
  const payload = JSON.parse(payloadBytes.toString('utf8'));
  /* keyId travels outside the payload for lookup, but the value we TRUST is the signed one. */
  if (payload.minKeyId && state.minKeyId && cmpKeyId(payload.minKeyId, state.minKeyId) < 0) {
    throw new Error('key retired');
  }
  return payload;
}
const cmpKeyId = (a, b) => String(a) < String(b) ? -1 : String(a) > String(b) ? 1 : 0;

function pickArtifact(payload) {
  const want = process.platform === 'win32' ? 'win32' : process.platform;
  const arch = process.arch;
  const list = Array.isArray(payload.artifacts) ? payload.artifacts : [];
  return list.find((a) => a && a.platform === want && (!a.arch || a.arch === arch)) || null;
}

function urlAllowed(u, isRedirect) {
  let parsed;
  try { parsed = new URL(u); } catch { return false; }
  if (parsed.protocol !== 'https:') return false;
  if (isRedirect) return parsed.hostname.endsWith(ARTIFACT_REDIRECT_SUFFIX);
  return parsed.hostname === ARTIFACT_HOST;
}

/* ── the check ──────────────────────────────────────────────────────────────────────────────────── */

async function checkNow(opts) {
  const force = !!(opts && opts.force);
  if (DISABLED || state.optOut) return null;
  const body = await getBounded(manifestUrl(), MANIFEST_MAX_BYTES, FETCH_TIMEOUT_MS);
  state.lastCheckedAt = Date.now();
  if (!body) { saveState(); return null; }

  let payload;
  try { payload = verifyManifest(JSON.parse(body.toString('utf8'))); }
  catch (e) { reportFailure('verify:' + e.message); saveState(); return null; }

  if (payload.channel && payload.channel !== CHANNEL) { saveState(); return null; }
  if (cmpVersion(payload.version, app.getVersion()) <= 0) { current = null; saveState(); return null; }

  /* Rollout. The bucket comes from the renderer, which owns the install id; it is not a security
     boundary, so a caller that never supplies one is simply always included. */
  if (!force && typeof payload.rollout === 'number' && payload.rollout < 100) {
    const bucket = opts && typeof opts.bucket === 'number' ? opts.bucket : 0;
    if (bucket >= payload.rollout) { current = null; saveState(); return null; }
  }

  /* A postponed version stays postponed, unless the release says it is important, in which case it
     comes back every launch - still dismissible, every time. */
  if (!force && !payload.important && state.postponedVersion === payload.version) {
    const age = Date.now() - (state.postponedAt || 0);
    if (age < POSTPONE_DAYS * 86400000) { current = null; saveState(); return null; }
  }

  const artifact = pickArtifact(payload);
  current = {
    version: String(payload.version),
    notes: String(payload.notes || ''),
    important: !!payload.important,
    artifact: artifact && urlAllowed(artifact.url, false) ? artifact : null
  };
  saveState();
  return current;
}

/* ── the download, and the only place a child process is ever spawned ───────────────────────────── */

async function installNow(onProgress) {
  if (busy) return { ok: false, reason: 'busy' };
  if (NOTIFY_ONLY) return { ok: false, reason: 'notify-only' };
  if (!current || !current.artifact) return { ok: false, reason: 'nothing-to-install' };
  const art = current.artifact;
  if (!urlAllowed(art.url, false)) return { ok: false, reason: 'host' };
  if (!/^[a-f0-9]{128}$/i.test(String(art.sha512))) return { ok: false, reason: 'no-hash' };

  busy = true;
  const dir = path.join(app.getPath('userData'), 'updates');
  const file = path.join(dir, 'dika-studio-' + current.version + '.exe');
  try {
    await fsp.mkdir(dir, { recursive: true });

    /* Free space first. The installer is ~175 MB, the unpacked app ~207 MB, and userData on the same
       disk holds the only copy of this person's work. Running it out of space is the one failure that
       could cost them something. */
    const need = (Number(art.sizeBytes) || 200e6) * 2;
    try {
      const st = await fsp.statfs(dir);
      if (st.bavail * st.bsize < need) { busy = false; return { ok: false, reason: 'disk' }; }
    } catch { /* statfs is unavailable on some filesystems; proceed rather than refuse */ }

    const bytes = await download(art.url, file, Number(art.sizeBytes) || 0, onProgress);
    if (!bytes) { await rm(file); busy = false; reportFailure('download', current.version); return { ok: false, reason: 'download' }; }

    /* Hash the file we are about to run, from the file we just wrote. */
    const got = await sha512(file);
    if (got.toLowerCase() !== String(art.sha512).toLowerCase()) {
      await rm(file);
      busy = false;
      reportFailure('hash-mismatch', current.version);
      /* Deliberately not retried. A mismatch is corruption or an attack, and both deserve to be seen
         rather than papered over by a second attempt that might succeed. */
      return { ok: false, reason: 'hash' };
    }

    /* NSIS: run it and let it replace us. `detached` so it survives our exit; the app quits itself so
       the installer is not fighting a locked file. */
    const child = spawn(file, ['--updated'], { detached: true, stdio: 'ignore' });
    child.unref();
    busy = false;
    return { ok: true, file };
  } catch (e) {
    await rm(file);
    busy = false;
    reportFailure('install:' + (e && e.message ? e.message : 'unknown'), current.version);
    return { ok: false, reason: 'error' };
  }
}

const rm = (p) => fsp.rm(p, { force: true }).catch(() => {});

function download(url, dest, expectedBytes, onProgress) {
  return new Promise((resolve) => {
    let hops = 0;
    const go = (u, isRedirect) => {
      if (!urlAllowed(u, isRedirect)) return resolve(false);
      const req = net.request({ url: u, method: 'GET', redirect: 'manual',
        headers: { 'user-agent': 'dika.studio-updater' } });
      req.on('redirect', (status, method, redirectUrl) => {
        if (++hops > MAX_REDIRECTS || !urlAllowed(redirectUrl, true)) { try { req.abort(); } catch {} return resolve(false); }
        try { req.abort(); } catch {}
        go(redirectUrl, true);
      });
      req.on('response', (res) => {
        if (res.statusCode !== 200) { try { req.abort(); } catch {} return resolve(false); }
        let seen = 0;
        const out = fs.createWriteStream(dest);
        res.on('data', (c) => {
          seen += c.length;
          /* A server that says nothing about length must not be able to fill the disk. */
          if (expectedBytes && seen > expectedBytes * 1.05 + 1024) { try { req.abort(); } catch {} out.destroy(); return resolve(false); }
          if (onProgress && expectedBytes) onProgress(Math.min(100, Math.round((seen / expectedBytes) * 100)));
        });
        pipeline(res, out).then(() => resolve(seen > 0)).catch(() => resolve(false));
      });
      req.on('error', () => resolve(false));
      req.end();
    };
    go(url, false);
  });
}

function sha512(file) {
  return new Promise((resolve, reject) => {
    const h = crypto.createHash('sha512');
    const s = fs.createReadStream(file);
    s.on('data', (d) => h.update(d));
    s.on('end', () => resolve(h.digest('hex')));
    s.on('error', reject);
  });
}

/* ── what the renderer may ask, and it is four questions with no arguments that steer anything ──── */

/* THE RELEASE PAGE, and it is DERIVED wherever it can be.
   The manifest's artifact URL already names the repository, by construction: the client only accepts
   `github.com/<org>/<repo>/releases/download/...`, so the first three segments of a verified URL are
   the repository this build is actually served from. Deriving it means the link cannot point at a
   different repository from the file - which is exactly the drift that had this constant naming one
   organisation while the website named another.
   The literal below is only the fallback for a client that has not verified a manifest yet. It is the
   real repository (owner, 2026-08-16) and it must stay identical to the site's default. */
const RELEASES_FALLBACK = 'https://github.com/karamuhammet/Open-Editor-Dika-Studio-Community/releases';

function releasesUrl() {
  const url = current && current.artifact && current.artifact.url;
  if (url) {
    const m = String(url).match(/^https:\/\/github\.com\/([^/]+)\/([^/]+)\//);
    if (m) return 'https://github.com/' + m[1] + '/' + m[2] + '/releases';
  }
  return RELEASES_FALLBACK;
}

function publicState() {
  return {
    enabled: !DISABLED && !state.optOut && !!UPDATE_PUBLIC_KEY,
    channel: CHANNEL,
    currentVersion: app.getVersion(),
    lastCheckedAt: state.lastCheckedAt || 0,
    optOut: !!state.optOut,
    notifyOnly: NOTIFY_ONLY,
    platformCanInstall: !NOTIFY_ONLY,
    available: current ? current.version : null,
    notes: current ? current.notes : '',
    important: current ? !!current.important : false,
    /* The page shows a link when we cannot install for them. It is a RELEASES page derived from the
       verified artifact URL, never a free-form link the manifest chose: the manifest may name an
       artifact, which we then pin and hash, and nothing else. */
    releasePage: releasesUrl()
  };
}

function postpone() {
  if (!current) return false;
  state.postponedVersion = current.version;
  state.postponedAt = Date.now();
  current = null;
  saveState();
  return true;
}

function setOptOut(v) { state.optOut = !!v; saveState(); return state.optOut; }

module.exports = {
  loadState, checkNow, installNow, publicState, postpone, setOptOut,
  openReleasePage: () => shell.openExternal(releasesUrl()),
  /* exported for the proof only */
  _internals: { cmpVersion, urlAllowed, verifyManifest, manifestUrl, pickArtifact }
};
